fsharp/emacs-fsharp-mode

Makefile
Different "curl -o" output name cause rebuilding $(ac_archive) target
each time.
Also define $(bin_d) as order-only-prerequisites to prevent
re-downloading each time $(bin_d) gets a new timestamp (when unziping
the distribution).
=> Fix $(ac_archive) target

fsharp-mode-completion.el
Even though the BOM from STDOUT is correctly handled by Emacs, there
is also a BOM present in STDERR. And there is no way to seperate STDOUT
and STDERR:
http://www.gnu.org/software/emacs/manual/html_node/elisp/Output-from-Processes.html
Emacs-devel discussion: https://lists.gnu.org/archive/html/emacs-devel/2015-06/msg00556.html
BTW: There might be timing issues, because I did not run into this problem on my faster system.
=> Remove BOM from process output

fsharp-mode.el
C-x C-e is a default keybinding for eval in elisp and clojure(cider), so why not for fsharp-mode, too?
=> Add C-x C-e as default keybinding for eval

inf-fsharp-mode.el
I use this setup for the custom:
(uniquify-buffer-name-style (quote reverse) nil (uniquify))
which leads to 
#silentCd    @"c:/cygwin/home/lenny/fsharp/test/src/test/Library.fs/test/src/test/fsharp/lenny/home/cygwin/";;
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
stdin(1,1): error FS2302: Directory    'c:/cygwin/home/lenny/fsharp/test/src/test/Library.fs/test/src/test/fsharp/lenny/home/cygwin/' doesn't exist
because the _buffer-name_ doesn't match the _buffer-file-name_
I also removed a redundant and nested use of _safe-excursion_
=> Fix fsi silent cd

fsharp-mode.el
=> Inhibit electric-indent for fsharp-mode buffers

fsharp-mode-completion.el
This reduces the "fsautocomplete" response size and thus improves elisp
parsing/filtering speed when using the "completion" command.
```company``` completion is much faster now when using modules with many values.
Maybe we can also get rid of ```fsharp-company-filter```?
BTW: Thanks for the company backend. I never looked back to autocomplete.
=> Use fsautocomplete prefix "StartsWith" filter

fsharp-mode.el
`company-quickhelp` uses `pos-tip`, which doesn't support terminals.
=> Unbreak company support on non-graphic displays

fsharp-mode-completion.el, test/Test1/NoProject.fs, test/integration-tests.el
Fixes completion errors when the current file is not part of a Project:
`
(error "Company: backend fsharp-ac/company-backend async timeout with args (candidates Sys)")
`
=> Fix async timeout no project

fsharp-mode-pkg.el, fsharp-mode.el
Fixes "Symbol's value as variable is void" error on (e.g.) C-c C-t
=> Fix use of popup

fsharp-mode-completion.el, fsharp-mode.el
This makes completions faster by not requiring a full parse to complete before issuing completions.
We parse once per line, and subsequent requests send the lineStr to FSAC. Corresponding FSAC PR incoming.
=> Faster completions

fsharp-mode-completion.el
This fixes a little annoyance I have when using company-mode. It sorts based on the case of the completion.
It doesn't always seem to work, but still seems like an improvement over the current code.
=> prefer exact case sort

fsharp-mode-font.el, test/apps/FSharp.Compatibility/Format.fs.faceup, test/apps/RecordHighlighting/Test.fsx, test/apps/RecordHighlighting/Test.fsx.faceup, test/fsharp-mode-font-tests.el
Ref #74
@Holtiton thanks for the good investigation. You can see here how added a new test and tried your fix, and it seems better but not quite perfect. If you install the `faceup` package, `eval-buffer` the test file and `M-x ert-run-tests-interactively` you can try it.
You'll see a difference of
```
((on-line 273
("        «k:let» «k:rec» «f:f» («v:searchPaths»: «t:SearchPath list») («v:ptr»: «t:nativeptr»«n:<searchpath_t>») =")
("        «k:let» «k:rec» «f:f» («v:searchPaths»: «t:SearchPath» «v:list») («v:ptr»: «t:nativeptr»«n:<searchpath_t>») =")))))
```
Which is indicating that in a case like:
```
type RecordTest7 =
{
something: int
another: string
third: int option
}
```
The `option` in `int option` is no longer highlighted. Any thoughts on how we could tweak the regex further?
By …
=> Record type highlighting

fsharp-mode.el, inf-fsharp-mode.el
I did a code cleanup of `inf-fsharp-mode` while working on `org-mode` _babel_ support for _f#:_:
` 2 files changed, 8 insertions(+), 13 deletions(-)`
Less code to maintain = less pain :smile:
=> Small code cleanup

test/integration-tests.el
Need to convert expected filename to an OS filename. Also use
`regexp-quote' because Windows backslash need to be escaped in regular
expressions. Refs #80.
=> Fix check-project-files on Windows

inf-fsharp-mode.el
Fixes issue when inferior fsi is started in a Tramp directory. Refs #66.
i.e.: Don't send Tramp names:
```
> 
#silentCd @"/scp:juergen@p.hoetzel.info:/home/juergen/fsharp/HParser/src/HParser/";;
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/home/juergen/fsharp/HParser/src/HParser/stdin(1,1): error FS2302: Directory '/scp:juergen@p.hoetzel.info:/home/juergen/fsharp/HParser/src/HParser/' doesn't exist
```
=> Inferior fsi: #silentcd to local directory

fsharp-mode-completion.el, test/Test1/Program.fs, test/integration-tests.el
Using type annotation without white-space triggers these errors.
First case of failure (wrong replacement):
```
type Dummy = Foo | Bar
let x:D
^ complete
->
let Dummy
```
the identifier is also replaced because `fsharp-ac-get-prefix` also matches the text before the colon.
Second case of failure (args-out-of-range error):
```
let dummy:D
^complete
->
Debugger entered--Lisp error: (args-out-of-range #("DBNull" 0 6 (annotation "C")) 0 7)
substring(#("DBNull" 0 6 (annotation "C")) 0 7)
```
this is because the prefix i"dummy:D" is longer than the candidates returned by _fsautocomplete.exe_
=> Fix completion of type annotated symbols

fsharp-mode-completion.el, fsharp-mode.el
Based on knowledge gained from  [Don't clobber company-backends](https://github.com/fsharp/emacs-fsharp-mode/pull/84):
- Don't restrict `company-backends` to `fsharp-ac/company-backend`, because users might have setup other useful backends
- Restrict the use of other backends to strings and comments
=> Don't clobber company-backends 2

README.md
Simple but somewhat important for those who are not using default 4 spaces per tab.
=> Add tab size manipulation note in README

fsharp-mode-indent.el
I removed "\" from regex, it seems escaping is not needed here and doesn't escape anything.
Works on the last line in a file now, too. See comment https://github.com/fsharp/emacs-fsharp-mode/issues/92#issuecomment-248735553
=> another fix for fsharp-end-of-block

CHANGELOG.md, fsharp-mode-font.el, fsharp-mode-pkg.el
Wires up existing imenu variables so they'll actually "work"; closes #98. All tests pass. Bumps version to 1.9.2.
=> Enable IMenu Support

fsharp-mode-completion.el, fsharp-mode.el
Instead return (prefix . t) in prefix command to let company-mode accept
prefix lengths less than `company-minimum-prefix-length'.
This prevents premature completion of other backends (like dabbrev).
Refs #102 and #101.
=> Dont change `company-minimum-prefix-length'

fsharp-mode-completion.el, fsharp-mode.el
This fixes invalid flycheck lint messages about trailing whitespace.
=> Don't send trailing newline to fsautocomplete

fsharp-mode.el
Instead make `indent-region-function` local in fsharp-mode buffers.
Fixes #107
=> Dont change default indent region function

flycheck-fsharp.el, fsharp-doc.el, fsharp-mode-completion.el, fsharp-mode.el
Flycheck's idle timer will attempt to check the buffer after a change, and it
requires its callback to be called when it does this.  We were not respecting
this fully, which caused Flycheck to stall/break.  The bug was due to an
interaction between the echo area typesig/symboluse lookups and Flycheck
attempting to perform a check for which it would never get a reply.  The issue
was that Flycheck tries to run a check via post-command-hook, so if the user
merely moved the cursor but did not enter text, Flycheck would try to run a
check and never get a reply because fsharp-ac-parse-current-buffer would
decide to not send anything to FSAC (it only runs if the buffer's tick has
changed or if fsharp-ac--last-parsed-buffer is not the current buffer).  As a
result, there would be no …
=> Fix Flycheck; don't busy wait in fsharp-doc-mode

fsharp-mode-font.el, fsharp-mode-indent.el, fsharp-mode.el, test/apps/FQuake3/NativeMappings.fs.faceup, test/apps/FSharp.Compatibility/Format.fs.faceup, test/apps/RecordHighlighting/Test.fsx.faceup, test/fsharp-mode-font-tests.el
This PR comes out of the proposal in #97. I'm opening it now for initial review; there's a small amount more clean-up and tidying that needs to be done before this gets merged, but I want to expose my thinking early and open this up for discussion. 
This PR:
1. Refactors the behemoth font locking regexen in to smaller, easier to re-use pieces.
2. Re-uses those pieces as possible.
3. Puts (most) of those pieces under unit test. 
4. Adds font locking for certain F# symbols. 
I think that last point is one I particularly want to discuss. My though is that F# uses operators of a lot more significance than other languages of my acquaintance, and many of them have a kind of structural importance. And: I wanted to start moderately. To that end, this PR adds font locking for `|`, `|> / ||> / …
=> Refactor Font Locking

CHANGELOG.md, fsharp-mode-font.el, test/apps/FQuake3/NativeMappings.fs.faceup, test/apps/FSharp.Compatibility/Format.fs.faceup, test/apps/RecordHighlighting/Test.fsx.faceup, test/fsharp-mode-font-tests.el
This PR cleans up some of the work from #114:
- Removes commented and dead code
- `eval-when-compile`s the main font-lock-keywords form
- Better font locking for active patterns
- Docstrings
- Naming
=> A little more tidying

fsharp-mode.el
@nosami  I don't know about the rationale setting this to `0.03` secons in `fsharp-mode` buffers.
I often get a disruptive completion popup while  still typing. It is exacerbated by the fact that we use a `min-prefix-length` of `0`.
I would prefer not changing this `defcustom`  and let Users customize it if they want faster/slower settings.
Any options?
:fireworks:
=> Don't change company-idle-delay

fsharp-mode-completion.el
The protocol chatter sent to FSAC to parse some code goes like this:
```
parse "filename"
...F# code...
...F# code...
...F# code...
<<EOF>>
```
`<<EOF>>` is not an actual EOF, but literally the string `<<EOF>>`, which must be
preceded by a newline and followed by a newline.
The issue was that typing at the end of the buffer would cause the buffer's
contents to be sent to FSAC, but because the last byte of the buffer would not
be the conventional appended-at-save newline, FSAC would be sent this instead:
```
parse "filename"
...F# code...
...F# code...
...F# code...<<EOF>
```
...and thus continue waiting for input indefinitely, causing things like type
info and Flycheck to stop working.
Fixes #119.
=> Fix FSAC hanging issue

fsharp-mode-completion.el
Hello there,
I am observing some serious freezes when using this F# mode on a medium sized project (F*) under linux with mono and intellisense activated. Here are 2 small fixes which should improve the situation : 
- The first one remove undo-history from the background fsharp-complete buffer by default. I can't see any valid reason to maintain this and It can grow very big.
- the second is a guard to prevent fsharp mode to hang on 0-sized answer from the background process.
=> Small fixes to try to prevent fsharp-mode to freeze all emacs

fsharp-mode-completion.el
Instead just log parsing errors and try to parse next line. Fixes #130.
=> Don't panic on malformed JSON (debug messages)

fsharp-mode.el
These commands were bound to 'C-c l' and 'C-c r', keys conventionally
reserved for the user.
https://www.gnu.org/software/emacs/manual/html_node/elisp/Key-Binding-Conventions.html
The choice of 'C-c <' and C-c >' is drawn from python-mode.
Resolves #135.
=> fsharp-shift-region-[left,right]: change bindings to 'C-c <' and 'C-c >'

.travis.yml, README.md, fsharp-mode-completion.el
As discussed in [Improve *fsharp-debug* logging](https://github.com/fsharp/emacs-fsharp-mode/issues/132)
- Log caller-function (when (>= fsharp-ac-debug 3))                                                                                                                                                                
- Supply format string instead of already formatted string                                                                                                                                                         
- Human readable timestamps                                                                                                                                                                                        
- Ensure newline before log message    
I hope this will …
=> Improved logging

fsharp-mode.el
Refs #150.
Just to handle missing commands gracefully.
=> Check for missing compile/build commands

fsharp-mode-font.el, test/apps/FSharp.Compatibility/Format.fs.faceup
This enhances both coloring (`let private f x` now colors `f` as a function) and imenu support (`f` is listed, not `private`).
=> Add access control keywords to declaration regexes

fsharp-mode-completion.el
One of the regexp used to calculate the prefix while doing auto-completion is matching too many things.
This stops matching `[` as a part of what's being auto-completed.
Should fix #161
=> Stop matching [ as part of normal residue.

.travis.yml, fsharp-mode-completion.el
Also add emacs-26-pretest and emacs-snapshot to build matrix.
=> Use emacs-travis.mk instead of deprecated evm

flycheck-fsharp.el, test/test-common.el
Prevents calling checker when FSharp.AutoComplete process is not
ready to handle requests. Refs #167
=> Flycheck: Add predicate function (WIP)

flycheck-fsharp.el, fsharp-mode-completion.el
[Improved fsautocomplete diagnostics](https://github.com/fsharp/emacs-fsharp-mode/issues/165)
=> Flycheck verify (WIP)

fsharp-mode-indent.el
`fsharp-goto-block-up' doesn't return non-nil if (point) was moved.
Refs #171
=> Fix phrase detection error

fsharp-mode-font.el
This commit fixes a bug in which only the final name in a multi-symbol active
record would be font locked. The trouble is that the regexp requires the closing
banana clip |) as part of the pattern; the final paren should be _optional_.
Thus, the only meaningful change is adding a ? inside the regexp. A newline is
introduced to make the whole thing slightly more readable.
=> Fix a small bug in font locking for active patterns

Makefile, README.md
This should be helpful for people running into #183 and related issues, and seems like a useful thing to be able to do in general.
=> Add the option to build and install with different versions of fsac

fsharp-mode.el
Newer versions of Mono have deprecated xbuild and encourage usage of the msbuild
command that ship with Mono instead. Picking xbuild as the default causes issues
with modern VS project files, which it does not understand. It should be
reasonably safe to prefer using msbuild over xbuild on any platform where
msbuild is found.
=> Set default build command to msbuild if it is found

fsharp-mode-indent.el
There are three examples I know of what this does:
Before this patch, we see the following three indentations happening:
```
type X =
····{
········field : WithType
········}
```
```
let foo =
····async {
········field : WithType
········}
```
```
let foo = seq {
········field : WithType
········}
```
Whereas with this patch, we instead get
```
type X =
····{
········field : WithType
····}
```
```
let foo =
····async {
········field : WithType
····}
```
```
let foo = seq {
····field : WithType
}
```
This, I believe, fixes #203.
=> Add curly brace as token that should be outdented

fsharp-mode-indent.el
If I press return when point is at the square in the following line of code:
```
let SigninButton = FunctionComponent.Of (fun (props : UntypedProps) ->▊
)
```
fsharp-mode helpfully indents for alignment:
```
let SigninButton = FunctionComponent.Of (fun (props : UntypedProps) ->
·········································▊
)
```
I prefer a less aligning indentation style, where I indent only by the same
amount any time it is legally possible to do so. In this case, what I wanted was
the more conservative
```
let SigninButton = FunctionComponent.Of (fun (props : UntypedProps) ->
····▊
)
```
This commit adds a customizeable variable that makes fsharp-mode indent in this
more conservative way instead.
=> Add setting for conservative indent on first line after bracket

README.md
Forge was a 404.
Melpa had a redirect, but now is pointing to the canonical one with https.
=> Corrected links to Forge and MELPA

eglot-fsharp.el
Remove zip after unzip. Fixes #236
=> Ensure a valid (windows) filename ist used for the temporary zip

eglot-fsharp.el
Hi,
I am using this for F# development on Windows where I am living with a few restrictions and it may be useful for others, too. I have not tested this with different setups.
Kind regards, Florian
=> Execute .NET framework binary directly when running on Windows

eglot-fsharp.el
Fixes issue #245.
A request to change the link from a non-downloadable link to a downloadable release link in the Github repository.
=> Installing of FsAutoComplete from github instead of appveyor.

.github/workflows/test.yml, Cask
This implementation is a hack:
- Cask still doesn't work on windows: https://github.com/cask/cask/pull/449. We use a checkout of this pull-request.
- Make doesn't work on windows: We use multiple "cask.bat" invocations to do the test.
The best long term solution seems to switch to eldev.
=> Add Github Action for windows-latest

eglot-fsharp.el
Setting `eglot-fsharp-server-version' to 'latest will always install
the latest fsautocomplete version.
At every start of `eglot-fsharp' it is checked if the installed
version is outdated.
The github version check is done only once per session, so performance
is not affected too much.
=> Add the possibility to always install/autoupdate to  the latest version

eglot-fsharp.el
This restores compatibility to Emacs 26.3. The native JSON functions
are only available since Emacs 27.1.
Issue introduced by #251 which uses native JSON
=> Use json-read instead of json-parse-buffer

eglot-fsharp.el
Refs #253
`eglot-fsharp` depends on `fsharp-mode`
=> Prepare split package

fsharp-mode-font.el, fsharp-mode-util.el, fsharp-mode.el
Emacs 25 ships with a sequence library named seq.el. This renders
dash.el completely obsolete.
=> Replace dash.el with seq.el

fsharp-mode.el
Fixes package-lint error:
eglot-fsharp.el:6:52 (package-lint-warning) Version dependency for fsharp-mode appears too high: try 1.9.15
=> Bump version

eglot-fsharp.el
False positive error was fixed in `package-lint`: https://github.com/purcell/package-lint/issues/202
=> Fix remaining package-lint errors: add jsonrpc explicitly

fsharp-mode-util.el, fsharp-mode.el
This commit https://github.com/fsharp/emacs-fsharp-mode/commit/93b3e0036121eec298fe26f1267dd61944612b7a removed dash.el dependency but some dash functions still used. This PR replaces dash functions/macros with standard library's functions/macros.
=> Replace dash functions and fix byte-compile warnings

fsharp-mode.el
The problem is described [here](https://github.com/syl20bnr/spacemacs/issues/11326). I haven't been writing much F# lately but I found that `emacs-scala-mode` has the same problem and this fix works well for it, so I thought I would submit it here too.
=> fix: `//`-comments filled incorrectly (`//` not acting as prefix)

fsharp-mode-font.el, test/fsharp-mode-font-tests.el
Currently, custom operators that contain pipe char sequence are colored partially.
Let's say we have operator `|>>` (monadic map in FSharpPlus and FParsec libs).
Part that contains pipe gets colored (`|>`), part that remains (`>`) stays default.
This PR sets all custom operators with pipe sequence to default.
=> Generic face for custom operators that contain pipe char sequence.

inf-fsharp-mode.el
I got the following error when launching REPL.
```
inferior-fsharp-mode: Symbol’s function definition is void: copy-seq
```
cl.el is deprecated since Emacs 27 and newer Emacs doesn't load by default. This file already loads `cl-lib` so it should use cl-lib functions.
=> Use cl-lib function instead of cl.el's one

eglot-fsharp.el
Prevent parsing failures when using non-C-locales
=> Use C-locale when interacting with "dotnet search"

eglot-fsharp.el
LANG=C workaround doesn't work on Windows
Fixes issue using german locale
```
Aktuelle Version: 0.54.0
```
did not match.
=> Generalize version string match

inf-fsharp-mode.el
Ensures line-buffering of inferior F# output.
Refs #293
=> Use pty for inferior F# process

eglot-fsharp.el
The latest version of fsautocomplete removed the `--background-service` parameter which makes eglot crash on startup. This swaps to the updated parameter for lsp mode.
`--background-service` has been deprecated, switch to experimental adaptive lsp service
change the `-v` parameter to `--verbose` to align with the documentation
=> Update console app parameters

.github/workflows/test.yml, README.org, eglot-fsharp.el, test/eglot-fsharp-integration-util.el, test/integration-tests.el
_Note: I reissued this PR from a branch so I could continue to develop my fork against master more easily with quelpa_
[FsAutoComplate](https://github.com/fsharp/FsAutoComplete) readme specifies additional settings provided to init that allow linting, and auto expansion of records, interfaces, etc to be supplied to eglot. 
This PR adds those parameters. I'm tempted to make this customizable via a variable, although I'm torn if it should be a single customizable value with the entire propertylist or individual values per config setting. 
I opted to leave the FsAutoComplete argument as a single customizable variable. This enables several additional parameters which are already supported by `eglot` and changes the default parameters to match the recommendations for all parameters to match …
=> Additional FsAutoComplete Parameters

eglot-fsharp.el
This PR should fix #331. 
It also updates the configuration parameters to match the settings used in Ionide which enables some extra code analysis settings (warnings in the configuration). 
This also ensures that parameters get passed correctly to the `workspace/didChangeConfiguration` as well, which was omitted in the previous settings PR.
=> Updating the configuration object to match Ionide configuration

fsharp-mode.el
The `nxml-mode` is built-in and will enable editing the fsproj files like they're xml files.
=> Enable nxml-mode for fsproj files

.github/workflows/test.yml, eglot-fsharp.el, test/eglot-fsharp-integration-util.el
Setting `eglot-fsharp-server-install-dir' to nil disables the custom "~/.emacs.d/FsAutoComplete/netcore/" tool path.
Fixes #341
=> Allow to use "fsautocomplete" from the global tool-path.

.github/pull_request_template.md, .github/workflows/test.yml, test/Test1/Test1.fsproj, test/eglot-fsharp-integration-util.el, test/integration-tests.el
Hello, hope you're good, with this PR I'm updating the GitHub Actions CI configuration.
Other than that, I'm adding a pull request template.
> [!WARNING]
> Some tests are broken. I tried to fix them but it didn't work out for now. This may be something that can be fixed with another PR later.
Please let me know what you think.
- https://github.com/fsharp/emacs-fsharp-mode/issues/343
=> Fix CI, comment some tests and add PR template

eglot-fsharp.el
I think it would be nice if it was possible to set the path to `fsautocomplete` if it is self-installed. In my case Emacs installed in Windows 10 defines the path `~/` as `C:/Users/<User>/AppData/Roaming`, but I would like to use `fsautocomplete` installed by myself.
So I made the path `~/.dotnet/tools/` as defcustom to be able to install my own path.
=> Added defcustom server path
