fsharp-mode.el

I think it could be sometimes quite useful.

.fsx files can be compiled with fsc, too

---

Makefile
fsharp-mode-completion.el
test/fsharp-mode-completion-tests.el

Change handling of tooltips for new format

Update to fsac 0.24.1

---

Makefile
fsharp-mode-completion.el
fsharp-mode-pkg.el
fsharp-mode.el
test/fsharp-mode-completion-tests.el
test/integration-tests.el
test/test-common.el

Very rough early visibility before I go out for the day :)
Working
- Completions after one char
Not working
- electric-dot
- sometimes returns wrong completions
- electric-backspace
- tests
- doc strings
- makes requests even while the completion popup is open
- currently case sensitive
I'm using it currently with the following settings in my personal config
```elisp
(eval-after-load 'company
'(add-to-list 'company-backends 'fsharp-ac/company-backend))
(setq company-idle-delay 0.03)
(setq company-minimum-prefix-length 0)
```
I'm not sure if the `add-to-list` should go in the plugin code or not yet.

Company mode (WIP)

---

README.md

- Mention forge for project management as it is probably more usable than
editing .fsproj files by hand
- Mention emacs mode works with F# 3.0 or higher

Forge + Version mention

---

fsharp-doc.el

fontify the doc string

---

inf-fsharp-mode.el

Fixes #72 
@colinbull this should address your problem, could you verify please?

Do not change current buffer when starting FSI

---

fsharp-mode.el

see https://www.emacswiki.org/emacs/AutoModeAlist

Fix auto-mode-alist

---

fsharp-mode-indent.el

fix fsharp-end-of-block, so it can handle F# attributes

---

LICENSE.md

add Apache License v2.0

---

inf-fsharp-mode.el

Define inferior-fsharp-mode as variant of comint mode

---

Makefile
test/test-common.el

As desired by https://github.com/fsharp/emacs-fsharp-mode/issues/97

Add a target for generating .faceup files

---

test/integration-tests.el

Add integration test for buffers without trailing newline

---

Makefile

Still needs manual testing, automated tests passed locally which I found a bit surprising.

Update to FSAC 0.34.0

---

fsharp-mode-util.el

Search msbuild.exe in Visual Studio 2017 directories

---

fsharp-mode.el

Don't change global value of `comment-indent-function'

---

fsharp-mode-completion.el
test/test-common.el

F# script files doesn't need to exist to be parsed

---

fsharp-mode-indent.el

Handle mutually recursive definitions in phrase detection

---

inf-fsharp-mode.el

Fix windows fsi process encoding

---

.travis.yml

Mitigate travis network timeout issues

---

Makefile
test/integration-tests.el
test/test-common.el

Merges #193  and fixes integration tests

Test relax tooltop match

---

Makefile

Override .NET Core SDK-Version when building FSAC

---

fsharp-mode.el

Use buffer-local version of company-quickhelp-mode

---

README.md

Adding some basic info about how to set it up using `use-package`

Add use-package info

---

README.org

- Convert Markdown to Org mode links

Doc update

---

eglot-fsharp.el

Update to latest fsautocomplete.exe release

---

fsharp-mode.el

Fixes #255 (interference with company-mode)

Remove unused local variables

---

eglot-fsharp.el

This patch fixed most issues from https://github.com/melpa/melpa/pull/7336.

Fixed for split eglot-fsharp package

---

Cask
README.org
fsharp-mode.el

- Merge #253 
- Eglot documentation update

Eglot split

---

inf-fsharp-mode.el
test/integration-tests.el

Prefer dotnet core FSI

---

.github/workflows/test.yml
README.org
eglot-fsharp.el
test/Test1/Pervasive.fs
test/Test1/Test1.fsproj
test/integration-tests.el

Followup of #288 
- Use "dotnet tool"
- Fix tests
- Add macos to build matrix

Use "dotnet tool" to manage "fsautocomplete"

---

fsharp-mode.el
test/integration-tests.el

`fsharp-mode-project-root`: Don't traverse filesystem twice

---

eglot-fsharp.el
test/integration-tests.el

Also install specific version in integration tests

---

.github/workflows/test.yml

Required for CI badge:
This reverts commit ab625668310bdf88390faa53c29eb5f2e90608f9.

Revert "Run CI on PR only"

---

eglot-fsharp.el

- Use temp-file instead of hardcoded stderr-file.
- Report the exact command that failed.

Refactor "dotnet tool (un)install fsautocomplete" error reporting

---

test/fsi-tests.el

Add FSI tests

---

eglot-fsharp.el

fsautocomplete dropped support for the full framework:
fsharp/FsAutoComplete#652

Remove support for .NET full framework

---

inf-fsharp-mode.el

Remove "echo" caused by pty-mode inferior fsharp process

---

eglot-fsharp.el

Install "fsautocomplete" on the remote host if `default-directory' is a tramp filename.
Add pipe-workaround for remote fsautocomplete processes: There seems to be a problem related to CRLF coded input in remote fsautocomplete processes. Wrapping the process using a cat pipe fixes the issue.
Even when setting `process-connection-type' to nil or 'pipe there is still a pseudo tty for the started remote process: https://www.gnu.org/software/emacs/manual/html_node/tramp/Remote-processes.html#Remote-process-connection-type
Fixes #324

Make `eglot-fsharp' tramp aware

---

README.org

fix(README.org): Fix Eldev link
